# Generated by Django 6.0.5 on 2026-09-02 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_productimage_image_sources_alter_brand_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "collection_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual — curated list"),
                            ("smart", "Smart — rule-based, auto-updating"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "smart_rule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("new_arrivals", "New Arrivals"),
                            ("restocked", "Recently Restocked"),
                            ("on_sale", "On Sale"),
                            ("best_sellers", "Best Sellers"),
                            ("low_stock", "Almost Gone"),
                        ],
                        max_length=20,
                    ),
                ),
                ("rule_window_days", models.PositiveIntegerField(default=14)),
                ("rule_threshold", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "banner_image",
                    models.ImageField(blank=True, upload_to="collections/banners/"),
                ),
                ("description", models.TextField(blank=True)),
                ("display_location", models.CharField(blank=True, max_length=50)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="coll_slug_idx"),
                    models.Index(fields=["is_active"], name="coll_active_idx"),
                    models.Index(fields=["collection_type"], name="coll_type_idx"),
                    models.Index(fields=["smart_rule"], name="coll_rule_idx"),
                    models.Index(fields=["display_location"], name="coll_loc_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("collection_type", "manual"),
                            (
                                "smart_rule__in",
                                (
                                    "new_arrivals",
                                    "restocked",
                                    "on_sale",
                                    "best_sellers",
                                    "low_stock",
                                ),
                            ),
                            _connector="OR",
                        ),
                        name="coll_smart_rule_requires_smart_type",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CollectionMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="collections.collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "pk"],
                "indexes": [
                    models.Index(fields=["product"], name="cm_product_idx"),
                    models.Index(
                        fields=["collection", "sort_order"], name="cm_coll_sort_idx"
                    ),
                ],
                "unique_together": {("collection", "product")},
            },
        ),
    ]
