# Generated by Django 6.0.5 on 2026-09-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="last_refreshed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
