# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collections", "0002_collection_last_refreshed_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(
                fields=["collection_type", "is_active"], name="coll_type_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collection",
            index=models.Index(fields=["sort_order"], name="coll_sort_idx"),
        ),
    ]
