# Generated by Django 6.0.5 on 2026-09-04 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderverification",
            name="resend_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
