# Generated by Django 6.0.5 on 2026-09-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_lookup_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="applied_discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
