# Generated by Django 6.0.5 on 2026-09-10 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_role"),
        ("orders", "0004_orderitem_applied_discount"),
        ("promotions", "0003_couponredemption_order"),
        ("shipping", "0003_alter_deliveryzone_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_source",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                    ("admin_manual", "Staff-Entered"),
                ],
                default="whatsapp",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="order",
            name="staff_created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["order_source"], name="order_source_idx"),
        ),
    ]
