# Generated by Django 6.0.5 on 2026-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_order_order_source_order_payment_reference_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="orderverification",
            name="ov_status_sent_idx",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("mpesa", "M-Pesa (confirmed manually by staff)"),
                    ("cod", "Cash on Delivery"),
                    ("bank_transfer", "Bank Transfer"),
                    ("invoice", "Invoice / Net Terms (B2B)"),
                ],
                default="mpesa",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="OrderVerification",
        ),
    ]
