# Generated by Django 6.0.5 on 2026-09-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_orderverification_ov_status_sent_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("mpesa", "M-Pesa (confirmed manually by staff)"),
                    ("cod", "Cash on Delivery"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default="mpesa",
                max_length=20,
            ),
        ),
    ]
