# Generated by Django 6.1 on 2026-09-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0002_remove_bundleitem_variant"),
        ("catalog", "0008_remove_productvariant_var_product_idx_and_more"),
        ("orders", "0008_staff_quoted_delivery"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="orderitem",
            name="order_item_sku_idx",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="variant_sku",
            new_name="product_sku",
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["product_sku"], name="order_item_sku_idx"),
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="variant_attributes",
        ),
    ]
