# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_options_address_addr_default_idx_and_more"),
        ("orders", "0009_remove_orderitem_order_item_sku_idx_and_more"),
        ("promotions", "0004_remove_discount_variants_alter_discount_scope"),
        ("shipping", "0005_deliveryarea_zone_active_county_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["payment_reference"], name="order_payref_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["placed_at"], name="order_placed_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["updated_at"], name="order_updated_idx"),
        ),
    ]
