# Generated by Django 6.1 on 2026-09-05 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_productimage_image_sources_alter_brand_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductViewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_key", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_events",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "created_at"], name="spv_product_time_idx"
                    ),
                    models.Index(fields=["created_at"], name="spv_created_idx"),
                    models.Index(
                        fields=["session_key", "created_at"], name="spv_session_idx"
                    ),
                ],
            },
        ),
    ]
