# Generated by Django 6.1 on 2026-09-05 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productimage_image_sources_alter_brand_logo_and_more"),
        ("social_proof", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productviewevent",
            name="bucket_started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name="productviewevent",
            constraint=models.UniqueConstraint(
                fields=("product", "session_key", "bucket_started_at"),
                name="spv_unique_view_per_bucket",
            ),
        ),
    ]
