# Generated by Django 6.0.5 on 2026-09-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_address_addr_user_default_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("manager", "Manager"),
                    ("support", "Support"),
                    ("analyst", "Analyst"),
                    ("courier", "Courier"),
                ],
                db_index=True,
                default="customer",
                max_length=12,
            ),
        ),
    ]
