# Generated by Django 6.0.5 on 2026-10-01 15:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_role_admin_only"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["is_default"], name="addr_default_idx"),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["created_at"], name="addr_created_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                django.db.models.functions.text.Lower("email"),
                name="user_email_lower_idx",
            ),
        ),
    ]
