# Generated by Django 6.1 on 2026-09-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bundleitem",
            name="variant",
        ),
    ]
