# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0002_remove_bundleitem_variant"),
        ("catalog", "0009_product_prod_active_discont_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="bundle",
            index=models.Index(
                fields=["is_active", "starts_at", "ends_at"],
                name="bundle_active_window_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="bundleitem",
            index=models.Index(fields=["bundle"], name="bitem_bundle_idx"),
        ),
        migrations.AddIndex(
            model_name="bundleitem",
            index=models.Index(fields=["product"], name="bitem_product_idx"),
        ),
        migrations.AddIndex(
            model_name="bundleitem",
            index=models.Index(
                fields=["bundle", "product"], name="bitem_bundle_product_idx"
            ),
        ),
    ]
