# Generated by Django 6.0.5 on 2026-09-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wishlistitem",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="wishlistitem",
            name="wish_user_idx",
        ),
        migrations.DeleteModel(
            name="WishlistItem",
        ),
    ]
