# Generated by Django 6.0.5 on 2026-09-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_alter_wishlistitem_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_user_idx",
        ),
        migrations.RemoveIndex(
            model_name="cart",
            name="cart_session_idx",
        ),
        migrations.RemoveConstraint(
            model_name="cart",
            name="cart_user_or_session_required",
        ),
        migrations.RemoveConstraint(
            model_name="cart",
            name="cart_not_both_user_and_session",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cartitem_cart_idx",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cartitem_variant_idx",
        ),
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cartitem_bundle_idx",
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="cartitem_exactly_one_target",
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="cartitem_quantity_gte_1",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="bundle",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="variant",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
