# Generated by Django 6.1 on 2026-09-24 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0002_remove_bundleitem_variant"),
        ("cart", "0004_initial"),
        ("catalog", "0007_remove_product_tracks_serial_numbers"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cartitem",
            name="cartitem_variant_idx",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cart_items",
                to="catalog.product",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(fields=["product"], name="cartitem_product_idx"),
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="variant",
        ),
    ]
