# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0003_bundle_bundle_active_window_idx_and_more"),
        ("cart", "0005_remove_cartitem_cartitem_variant_idx_and_more"),
        ("catalog", "0009_product_prod_active_discont_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cartitem",
            index=models.Index(
                fields=["cart", "product"], name="cartitem_cart_prod_idx"
            ),
        ),
    ]
