# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inquiries", "0001_initial"),
        ("orders", "0009_remove_orderitem_order_item_sku_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inquiry",
            index=models.Index(fields=["created_at"], name="inq_created_idx"),
        ),
    ]
