# Generated by Django 6.0.5 on 2026-09-04 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0004_orderitem_applied_discount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("item_received", "Item Received"),
                            ("refunded", "Refunded"),
                            ("replaced", "Replaced"),
                            ("closed", "Closed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "requested_resolution",
                    models.CharField(
                        choices=[
                            ("refund", "Refund"),
                            ("replacement", "Replacement"),
                            ("store_credit", "Store Credit"),
                        ],
                        default="refund",
                        max_length=20,
                    ),
                ),
                (
                    "restocking_fee_applied",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "refund_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mpesa_b2c", "M-Pesa B2C Payout"),
                            ("card_reversal", "Card Reversal"),
                            ("store_credit", "Store Credit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="return_requests",
                        to="orders.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_requests",
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnRequestStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(max_length=20)),
                ("note", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="return_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="returns.returnrequest",
                    ),
                ),
            ],
            options={
                "ordering": ["changed_at", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["order"], name="return_order_idx"),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["order_item"], name="return_order_item_idx"),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(
                fields=["status", "created_at"], name="return_status_created_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="returnrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("restocking_fee_applied__gte", 0),
                    models.Q(
                        ("refund_amount__isnull", True),
                        ("refund_amount__gte", 0),
                        _connector="OR",
                    ),
                ),
                name="return_money_fields_nonnegative",
            ),
        ),
        migrations.AddIndex(
            model_name="returnrequeststatushistory",
            index=models.Index(
                fields=["return_request", "changed_at"], name="rsh_req_changed_idx"
            ),
        ),
    ]
