# Generated by Django 6.0.5 on 2026-09-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_orderitem_applied_discount"),
        ("returns", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="returnrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("status", "rejected"), _negated=True),
                    ("order_item__isnull", False),
                ),
                fields=("order", "order_item"),
                name="return_one_per_line_not_rejected",
            ),
        ),
    ]
