# Generated by Django 6.0.5 on 2026-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0003_returnrequest_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="returnrequest",
            name="refund_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mpesa_b2c", "M-Pesa B2C Payout"),
                    ("store_credit", "Store Credit"),
                ],
                max_length=20,
            ),
        ),
    ]
