# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_order_payref_idx_order_order_placed_idx_and_more"),
        ("returns", "0005_refund_method_plain_text"),
        (
            "support",
            "0004_ticket_ticket_category_idx_ticket_ticket_created_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["created_at"], name="return_created_idx"),
        ),
        migrations.AddIndex(
            model_name="returnrequest",
            index=models.Index(fields=["resolved_at"], name="return_resolved_idx"),
        ),
    ]
