# Generated by Django 6.0.5 on 2026-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(upload_to="content/banners/")),
                ("link_url", models.CharField(blank=True, max_length=500)),
                ("placement", models.CharField(max_length=50)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["placement", "sort_order", "pk"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "placement", "sort_order"],
                        name="bn_active_placement_idx",
                    ),
                    models.Index(
                        fields=["starts_at", "ends_at"], name="bn_schedule_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("body", models.TextField()),
                ("is_published", models.BooleanField(default=True)),
                ("meta_title", models.CharField(blank=True, max_length=255)),
                ("meta_description", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title", "pk"],
                "indexes": [
                    models.Index(
                        fields=["is_published", "slug"], name="cp_published_slug_idx"
                    )
                ],
            },
        ),
    ]
