# Generated by Django 6.0.5 on 2026-09-08 03:49

from django.db import migrations, models

import apps.catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="banner",
            name="bn_active_placement_idx",
        ),
        migrations.RemoveIndex(
            model_name="banner",
            name="bn_schedule_idx",
        ),
        migrations.AlterField(
            model_name="banner",
            name="image",
            field=models.ImageField(
                upload_to="content/banners/",
                validators=[apps.catalog.validators.validate_image_upload],
            ),
        ),
    ]
