# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_remove_banner_bn_active_placement_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="banner",
            index=models.Index(
                fields=["is_active", "placement"], name="banner_active_place_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="banner",
            index=models.Index(fields=["sort_order"], name="banner_sort_idx"),
        ),
    ]
