# Generated by Django 6.1 on 2026-08-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.CharField(default="My Store", max_length=255)),
                ("tagline", models.CharField(blank=True, max_length=255)),
                ("domain", models.CharField(blank=True, max_length=255)),
                ("logo", models.ImageField(blank=True, upload_to="site/logo/")),
                ("favicon", models.ImageField(blank=True, upload_to="site/favicon/")),
                ("theme", models.JSONField(default=dict)),
                ("settings", models.JSONField(default=dict)),
                ("contact_email", models.EmailField(blank=True, max_length=254)),
                ("support_phone", models.CharField(blank=True, max_length=20)),
                ("social_links", models.JSONField(blank=True, default=dict)),
                ("kra_pin", models.CharField(blank=True, max_length=20)),
                (
                    "business_registration_number",
                    models.CharField(blank=True, max_length=50),
                ),
                ("physical_address", models.TextField(blank=True)),
                ("return_policy_text", models.TextField(blank=True)),
                ("cooling_off_period_days", models.PositiveIntegerField(default=7)),
                (
                    "standard_vat_rate",
                    models.DecimalField(decimal_places=2, default=16.0, max_digits=5),
                ),
            ],
        ),
    ]
