# Generated by Django 6.1 on 2026-08-30 10:32

from django.db import migrations, models

import apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="settings",
            field=models.JSONField(default=apps.core.models.default_site_settings),
        ),
    ]
