# Generated by Django 6.0.5 on 2026-09-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_siteconfig_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="order_intake_email",
            field=models.EmailField(
                blank=True,
                help_text="Mailbox that receives customer order emails.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="whatsapp_number",
            field=models.CharField(
                blank=True,
                help_text="Business WhatsApp number in international format, e.g. 254712345678.",
                max_length=20,
            ),
        ),
    ]
