# Generated by Django 6.1 on 2026-09-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_drop_retired_app_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="facebook_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Full Facebook page URL, blank to hide the link.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="instagram_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Full Instagram profile URL, blank to hide the link.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="tiktok_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Full TikTok profile URL, blank to hide the link.",
            ),
        ),
    ]
