# Generated by Django 6.0.5 on 2026-09-03 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bundles", "0001_initial"),
        ("catalog", "0004_productimage_image_sources_alter_brand_logo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percent", "Percentage"),
                            ("fixed", "Fixed Amount"),
                            ("free_shipping", "Free Shipping"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                (
                    "usage_limit_total",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("usage_limit_per_user", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("stackable_with_discounts", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applies_to_categories",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to="catalog.category"
                    ),
                ),
                (
                    "applies_to_products",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to="catalog.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CouponRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="promotions.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_redemptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-redeemed_at"],
            },
        ),
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("badge_text", models.CharField(blank=True, max_length=50)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("variant", "Specific Variant(s)"),
                            ("product", "Specific Product(s)"),
                            ("category", "Category"),
                            ("brand", "Brand"),
                            ("bundle", "Bundle"),
                            ("sitewide", "Sitewide"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("fixed", "Fixed Amount")],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.PositiveIntegerField(default=0)),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                ("redemption_count", models.PositiveIntegerField(default=0)),
                ("applies_within_bundles", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brands",
                    models.ManyToManyField(
                        blank=True, related_name="discounts", to="catalog.brand"
                    ),
                ),
                (
                    "bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discounts",
                        to="bundles.bundle",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="discounts", to="catalog.category"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="discounts", to="catalog.product"
                    ),
                ),
                (
                    "variants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discounts",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["code"], name="coup_code_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["is_active"], name="coup_active_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["starts_at"], name="coup_start_idx"),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(fields=["ends_at"], name="coup_end_idx"),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(fields=["coupon"], name="red_coupon_idx"),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(fields=["user"], name="red_user_idx"),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(fields=["redeemed_at"], name="red_at_idx"),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(fields=["scope"], name="disc_scope_idx"),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(fields=["is_active"], name="disc_active_idx"),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(fields=["starts_at"], name="disc_start_idx"),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(fields=["ends_at"], name="disc_end_idx"),
        ),
    ]
