# Generated by Django 6.0.5 on 2026-09-04 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("promotions", "0002_alter_coupon_value_alter_discount_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="couponredemption",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coupon_redemptions",
                to="orders.order",
            ),
        ),
    ]
