# Generated by Django 6.1 on 2026-09-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("promotions", "0003_couponredemption_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="variants",
        ),
        migrations.AlterField(
            model_name="discount",
            name="scope",
            field=models.CharField(
                choices=[
                    ("product", "Specific Product(s)"),
                    ("category", "Category"),
                    ("brand", "Brand"),
                    ("bundle", "Bundle"),
                    ("sitewide", "Sitewide"),
                ],
                max_length=20,
            ),
        ),
    ]
