# Generated by Django 6.0.5 on 2026-10-01 15:50

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0003_bundle_bundle_active_window_idx_and_more"),
        ("catalog", "0009_product_prod_active_discont_idx_and_more"),
        ("orders", "0010_order_order_payref_idx_order_order_placed_idx_and_more"),
        ("promotions", "0004_remove_discount_variants_alter_discount_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                django.db.models.functions.text.Lower("code"),
                name="coup_code_lower_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["is_active", "starts_at", "ends_at"],
                name="coup_active_window_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="couponredemption",
            index=models.Index(fields=["coupon", "user"], name="red_coupon_user_idx"),
        ),
        migrations.AddIndex(
            model_name="discount",
            index=models.Index(
                fields=["is_active", "starts_at", "ends_at"],
                name="disc_active_window_idx",
            ),
        ),
    ]
