# Generated by Django 6.0.5 on 2026-09-04 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0004_orderitem_applied_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="MpesaB2CPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("return_refund", "Return/Refund"),
                            ("order_cancellation", "Order Cancellation Refund"),
                            ("other", "Other"),
                        ],
                        default="return_refund",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("conversation_id", models.CharField(max_length=100, unique=True)),
                (
                    "originator_conversation_id",
                    models.CharField(blank=True, max_length=100),
                ),
                ("mpesa_receipt_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("raw_callback", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2c_payouts",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["conversation_id"], name="b2c_conversation_idx"
                    ),
                    models.Index(
                        fields=["order", "status"], name="b2c_order_status_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MpesaTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("checkout_request_id", models.CharField(max_length=100, unique=True)),
                ("merchant_request_id", models.CharField(blank=True, max_length=100)),
                ("mpesa_receipt_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled by user"),
                            ("timeout", "Timeout"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("result_code", models.CharField(blank=True, max_length=10)),
                ("result_desc", models.CharField(blank=True, max_length=255)),
                ("raw_callback", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mpesa_transactions",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["checkout_request_id"], name="mpesa_checkout_req_idx"
                    ),
                    models.Index(
                        fields=["order", "status"], name="mpesa_order_status_idx"
                    ),
                    models.Index(fields=["status"], name="mpesa_status_idx"),
                    models.Index(fields=["created_at"], name="mpesa_created_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("transaction_id", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(max_length=20)),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["order"], name="payment_order_idx"),
                    models.Index(
                        fields=["provider", "status"], name="payment_prov_status_idx"
                    ),
                ],
            },
        ),
    ]
