# Generated by Django 6.0.5 on 2026-09-04 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesatransaction",
            name="needs_reconciliation",
            field=models.BooleanField(default=False),
        ),
    ]
