# Generated by Django 6.0.5 on 2026-09-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_mpesatransaction_needs_reconciliation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                max_length=20,
            ),
        ),
    ]
