# Generated by Django 6.0.5 on 2026-09-04 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_status"),
        ("returns", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mpesab2cpayout",
            name="return_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="b2c_payouts",
                to="returns.returnrequest",
            ),
        ),
    ]
