# Generated by Django 6.0.5 on 2026-09-06 11:26

from django.db import migrations, models


def null_out_empty_dedup_keys(apps, schema_editor):
    """Replace historically stored empty-string deduplication keys with NULL."""
    MpesaTransaction = apps.get_model("payments", "MpesaTransaction")
    MpesaTransaction.objects.filter(checkout_request_id="").update(
        checkout_request_id=None
    )
    MpesaB2CPayout = apps.get_model("payments", "MpesaB2CPayout")
    MpesaB2CPayout.objects.filter(conversation_id="").update(conversation_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_mpesab2cpayout_return_request"),
    ]

    operations = [
        migrations.RunPython(null_out_empty_dedup_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="mpesab2cpayout",
            name="conversation_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="mpesatransaction",
            name="checkout_request_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
