# Generated by Django 6.1 on 2026-09-02 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0004_productimage_image_sources_alter_brand_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [models.Index(fields=["name"], name="wh_name_idx")],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("reserved", models.PositiveIntegerField(default=0)),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_records",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.warehouse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("fulfilled", "Fulfilled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.inventory",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "expires_at"], name="resv_status_expiry_idx"
                    ),
                    models.Index(fields=["inventory"], name="resv_inventory_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SerialUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=150, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                            ("returned", "Returned"),
                            ("defective", "Defective"),
                        ],
                        default="in_stock",
                        max_length=20,
                    ),
                ),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="serial_units",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["received_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["variant", "warehouse", "status"],
                        name="serial_vw_s_idx",
                    ),
                    models.Index(fields=["status"], name="serial_status_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["variant"], name="inv_variant_idx"),
        ),
        migrations.AddIndex(
            model_name="inventory",
            index=models.Index(fields=["warehouse"], name="inv_wh_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__lte", models.F("quantity"))),
                name="inv_reserved_lte_quantity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventory",
            unique_together={("variant", "warehouse")},
        ),
    ]
