# Generated by Django 6.1 on 2026-09-02 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productimage_image_sources_alter_brand_logo_and_more"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMovementLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("receive_count", "Receive Count"),
                            ("receive_serial", "Receive Serial"),
                            ("release", "Release"),
                            ("serial_status", "Serial Status Change"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_change", models.IntegerField(default=0)),
                ("reserved_change", models.IntegerField(default=0)),
                ("serial_number", models.CharField(blank=True, max_length=150)),
                ("from_status", models.CharField(blank=True, max_length=20)),
                ("to_status", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="serialunit",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="serial_units",
                to="inventory.stockreservation",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="serialunit",
            index=models.Index(fields=["reservation"], name="serial_resv_idx"),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="inv_quantity_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__gte", 0)), name="inv_reserved_gte_0"
            ),
        ),
        migrations.AddField(
            model_name="stockmovementlog",
            name="inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movement_logs",
                to="inventory.inventory",
            ),
        ),
        migrations.AddField(
            model_name="stockmovementlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movement_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="stockmovementlog",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_movement_logs",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockmovementlog",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movement_logs",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovementlog",
            index=models.Index(fields=["created_at"], name="sml_created_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovementlog",
            index=models.Index(fields=["inventory"], name="sml_inventory_idx"),
        ),
        migrations.AddIndex(
            model_name="stockmovementlog",
            index=models.Index(fields=["variant"], name="sml_variant_idx"),
        ),
    ]
