# Generated by Django 6.0.5 on 2026-09-03 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stockmovementlog_serialunit_reservation_and_more"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serialunit",
            name="order_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="serial_units",
                to="orders.orderitem",
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="order_item",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation",
                to="orders.orderitem",
            ),
        ),
    ]
