# Generated by Django 6.0.5 on 2026-09-06 09:37

from django.db import migrations, models

import apps.support.models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketmessage",
            name="attachment",
            field=models.FileField(
                blank=True, upload_to=apps.support.models.ticket_attachment_path
            ),
        ),
    ]
