# Generated by Django 6.0.5 on 2026-09-11 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_attachment_upload_path"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="chatmessage",
            name="chatmsg_session_sent_idx",
        ),
        migrations.RemoveIndex(
            model_name="chatsession",
            name="chat_user_started_idx",
        ),
        migrations.RemoveIndex(
            model_name="chatsession",
            name="chat_agent_ended_idx",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="assigned_agent",
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="ChatSession",
        ),
    ]
