# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_order_order_payref_idx_order_order_placed_idx_and_more"),
        ("support", "0003_remove_chatmessage_chatmsg_session_sent_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["category"], name="ticket_category_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(fields=["created_at"], name="ticket_created_idx"),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["status", "created_at"], name="ticket_status_created_idx"
            ),
        ),
    ]
