# Generated by Django 6.0.5 on 2026-09-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0002_stockmovementlog_serialunit_reservation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county", models.CharField(max_length=100)),
                ("area_name", models.CharField(max_length=255)),
                ("base_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "per_kg_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("estimated_days", models.PositiveIntegerField(default=2)),
                ("courier_partner", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["county", "area_name"],
                "indexes": [
                    models.Index(fields=["is_active"], name="zone_active_idx"),
                    models.Index(fields=["county"], name="zone_county_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="WarehouseZonePriority",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.PositiveIntegerField(default=0)),
                (
                    "delivery_zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warehouse_priorities",
                        to="shipping.deliveryzone",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["priority"],
                "indexes": [
                    models.Index(fields=["warehouse"], name="wzp_warehouse_idx")
                ],
                "unique_together": {("delivery_zone", "warehouse")},
            },
        ),
    ]
