# Generated by Django 6.0.5 on 2026-09-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stockmovementlog_serialunit_reservation_and_more"),
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="warehousezonepriority",
            options={"ordering": ["priority", "id"]},
        ),
        migrations.AlterUniqueTogether(
            name="warehousezonepriority",
            unique_together={
                ("delivery_zone", "priority"),
                ("delivery_zone", "warehouse"),
            },
        ),
    ]
