# Generated by Django 6.0.5 on 2026-09-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0002_alter_warehousezonepriority_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="deliveryzone",
            unique_together={("county", "area_name")},
        ),
        migrations.AddConstraint(
            model_name="deliveryzone",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_fee__gte", 0)), name="dz_base_fee_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryzone",
            constraint=models.CheckConstraint(
                condition=models.Q(("per_kg_rate__gte", 0)), name="dz_per_kg_rate_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryzone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("free_shipping_threshold__isnull", True),
                    ("free_shipping_threshold__gt", 0),
                    _connector="OR",
                ),
                name="dz_threshold_null_or_positive",
            ),
        ),
    ]
