# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0004_deliveryarea"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="deliveryarea",
            index=models.Index(
                fields=["is_active", "county"], name="zone_active_county_idx"
            ),
        ),
    ]
