# Generated by Django 6.1 on 2026-09-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_product_prod_specs_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="prod_name_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["product_type"], name="prod_ptype_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["tax_class"], name="prod_taxclass_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["average_rating"], name="prod_rating_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["review_count"], name="prod_review_idx"),
        ),
    ]
