# Generated by Django 6.1 on 2026-09-01 19:12

from django.db import migrations, models

import apps.catalog.validators


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_prod_name_idx_product_prod_ptype_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_sources',
            field=models.JSONField(blank=True, default=list, help_text='Processed variant metadata: width, format, and URL per image.'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.ImageField(blank=True, upload_to='brands/', validators=[apps.catalog.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/', validators=[apps.catalog.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='product',
            name='datasheet_pdf',
            field=models.FileField(blank=True, upload_to='products/datasheets/', validators=[apps.catalog.validators.validate_pdf_upload]),
        ),
        migrations.AlterField(
            model_name='product',
            name='installation_guide_pdf',
            field=models.FileField(blank=True, upload_to='products/guides/', validators=[apps.catalog.validators.validate_pdf_upload]),
        ),
        migrations.AlterField(
            model_name='product',
            name='manual_pdf',
            field=models.FileField(blank=True, upload_to='products/manuals/', validators=[apps.catalog.validators.validate_pdf_upload]),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.CheckConstraint(condition=models.Q(('parent', models.F('pk')), _negated=True), name='category_no_self_parent'),
        ),
        migrations.AddConstraint(
            model_name='relatedproduct',
            constraint=models.UniqueConstraint(fields=('product', 'related_product'), name='unique_related_product_link'),
        ),
        migrations.AddConstraint(
            model_name='relatedproduct',
            constraint=models.CheckConstraint(condition=models.Q(('product', models.F('related_product')), _negated=True), name='related_product_no_self_link'),
        ),
    ]
