# Generated by Django 6.0.5 on 2026-09-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productimage_image_sources_alter_brand_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="stock_status_override",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Automatic (from inventory counts)"),
                    ("in_stock", "In Stock"),
                    ("low_stock", "Low Stock"),
                    ("out_of_stock", "Out of Stock"),
                ],
                default="",
                help_text="Staff-set display override. Blank follows inventory counts.",
                max_length=20,
            ),
        ),
    ]
