# Generated by Django 6.0.5 on 2026-09-12 08:20

from django.db import migrations, models


def _carry_overrides_forward(apps, schema_editor):
    """Copy non-blank display overrides into the new manual flag."""
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    for value in ("in_stock", "low_stock", "out_of_stock"):
        ProductVariant.objects.filter(stock_status_override=value).update(
            stock_status=value
        )


def _carry_overrides_backward(apps, schema_editor):
    """Restore overrides from the manual flag on reverse migration."""
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    for value in ("in_stock", "low_stock", "out_of_stock"):
        ProductVariant.objects.filter(stock_status=value).update(
            stock_status_override=value
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_productvariant_stock_status_override"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="stock_status",
            field=models.CharField(
                choices=[
                    ("in_stock", "In Stock"),
                    ("low_stock", "Low Stock"),
                    ("out_of_stock", "Out of Stock"),
                ],
                default="in_stock",
                help_text="Staff-set availability. No quantity is tracked behind it.",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            _carry_overrides_forward, reverse_code=_carry_overrides_backward
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="stock_status_override",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="stock_status_text",
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["stock_status"], name="var_stock_status_idx"),
        ),
    ]
