# Generated by Django 6.0.5 on 2026-09-12 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_remove_productvariant_stock_status_override_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tracks_serial_numbers",
        ),
    ]
