# Generated by Django 6.1 on 2026-09-24 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bundles", "0002_remove_bundleitem_variant"),
        ("cart", "0005_remove_cartitem_cartitem_variant_idx_and_more"),
        ("catalog", "0007_remove_product_tracks_serial_numbers"),
        ("promotions", "0004_remove_discount_variants_alter_discount_scope"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="productvariant",
            name="var_product_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="var_sku_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="var_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="var_attrs_gin_idx",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="var_stock_status_idx",
        ),
        migrations.RemoveIndex(
            model_name="pricingtier",
            name="tier_var_qty_idx",
        ),
        migrations.AddField(
            model_name="pricingtier",
            name="product",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricing_tiers",
                to="catalog.product",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="pricingtier",
            index=models.Index(
                fields=["product", "min_quantity"], name="tier_prod_qty_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["stock_status"], name="prod_stock_status_idx"),
        ),
        migrations.RemoveField(
            model_name="pricingtier",
            name="variant",
        ),
        migrations.DeleteModel(
            name="ProductVariant",
        ),
    ]
