# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_remove_productvariant_var_product_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "is_discontinued"], name="prod_active_discont_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["is_discontinued"], name="prod_discont_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="prod_price_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["last_restocked_at"], name="prod_restocked_idx"),
        ),
    ]
