# Generated by Django 6.1 on 2026-10-02 11:21
#
# Trigram GIN indexes over the free-text search fields so ``icontains``
# matching (used by the public product search) is index-backed instead of
# a sequential scan. ``pg_trgm`` is a Postgres-only extension, so its
# creation is skipped on other backends (the test suite runs on SQLite).

import django.contrib.postgres.indexes
import django.contrib.postgres.operations
from django.db import migrations


class TrigramExtensionIfPostgres(django.contrib.postgres.operations.TrigramExtension):
    """Create ``pg_trgm`` on Postgres; no-op on any other backend."""

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        """Create the extension only where it exists.

        Args:
            app_label (str): the app the migration belongs to.
            schema_editor: the backend schema editor.
            from_state: the project state before this operation.
            to_state: the project state after this operation.
        """
        if schema_editor.connection.vendor == "postgresql":
            super().database_forwards(app_label, schema_editor, from_state, to_state)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_prod_active_discont_idx_and_more"),
    ]

    operations = [
        TrigramExtensionIfPostgres(),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="prod_name_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["sku"], name="prod_sku_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["short_description"],
                name="prod_short_desc_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["description"],
                name="prod_desc_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
