# Generated by Django 6.0.5 on 2026-09-10 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_productvariant_stock_status_override"),
        ("orders", "0005_order_order_source_order_payment_reference_and_more"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productquestion",
            name="submitter_contact",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="productquestion",
            name="submitter_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="review",
            name="submitter_contact",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="review",
            name="submitter_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="reviewphoto",
            name="session_key",
            field=models.CharField(
                blank=True,
                help_text="Server-issued guest session that uploaded the photo.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="productquestion",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="productquestion",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reviewphoto",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "submitter_contact"], name="rev_product_contact_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewphoto",
            index=models.Index(fields=["session_key"], name="revp_session_idx"),
        ),
    ]
