# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_prod_active_discont_idx_and_more"),
        ("orders", "0010_order_order_payref_idx_order_order_placed_idx_and_more"),
        ("reviews", "0002_productquestion_submitter_contact_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(
                fields=["is_approved", "-created_at"], name="pq_approved_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["is_approved", "-created_at"], name="rev_approved_created_idx"
            ),
        ),
    ]
