# Generated by Django 6.1 on 2026-09-01 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")],
                        default="sms",
                        max_length=10,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("test", "Internal Test"),
                            ("otp", "One-Time Password"),
                            ("order_update", "Order Status Update"),
                            ("promotional", "Promotional"),
                            ("transactional", "Transactional"),
                        ],
                        default="test",
                        max_length=20,
                    ),
                ),
                (
                    "recipient",
                    models.CharField(
                        help_text="Phone number (E.164) or email address.",
                        max_length=15,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "channel"],
                        name="notificatio_recipie_b00fb5_idx",
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_a242db_idx"
                    ),
                    models.Index(
                        fields=["purpose"], name="notificatio_purpose_b287ee_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="notificatio_created_01830a_idx"
                    ),
                ],
            },
        ),
    ]
