# Generated by Django 6.0.5 on 2026-09-02 15:34

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationlog",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Client-supplied dedup key; prevents duplicate sends on retry.",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="segments",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="SMS segment count reported by the provider.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notificationlog",
            name="recipient",
            field=models.CharField(
                help_text="Phone number (E.164) or email address.",
                max_length=254,
                validators=[django.core.validators.MaxLengthValidator(254)],
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["idempotency_key"], name="notificatio_idempot_d54945_idx"
            ),
        ),
    ]
