# Generated by Django 6.0.5 on 2026-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationlog_idempotency_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationlog",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("test", "Internal Test"),
                    ("order_update", "Order Status Update"),
                    ("promotional", "Promotional"),
                    ("transactional", "Transactional"),
                ],
                default="test",
                max_length=20,
            ),
        ),
    ]
