# Generated by Django 6.0.5 on 2026-10-01 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_alter_notificationlog_purpose"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["provider_message_id"], name="notif_provider_msg_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(fields=["channel"], name="notif_channel_idx"),
        ),
    ]
